name: Rust
on:
  push:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - windows-2019
        rust_version: [stable, nightly, 1.69]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          default: true
      - name: Benchmark
        working-directory: bindings/rust
        run: cargo bench
